# Generated by Django 4.1.1 on 2022-10-23 04:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeehouse',
            name='coffee_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='coffees_images/'),
        ),
    ]
